set(SCHEMA_HEADER_PATH "${OUTPUT_HEADER}")
set(SCHEMA_SQL_PATH "${INPUT_SCHEMA}")

string(TIMESTAMP GEN_TIMESTAMP "%Y-%m-%d %H:%M:%S")
set(GEN_COMMENT "// Generated by generate_schema_header.cmake on ${GEN_TIMESTAMP}\n")

message(STATUS "SCHEMA_SQL_PATH: ${SCHEMA_SQL_PATH}")
file(READ "${SCHEMA_SQL_PATH}" SCHEMA_CONTENTS)

file(WRITE "${SCHEMA_HEADER_PATH}" "${GEN_COMMENT}")
file(APPEND "${SCHEMA_HEADER_PATH}" "#pragma once\n")
file(APPEND "${SCHEMA_HEADER_PATH}" "static const char* navdata_schema = R\"sql(\n")
file(APPEND "${SCHEMA_HEADER_PATH}" "${SCHEMA_CONTENTS}")
file(APPEND "${SCHEMA_HEADER_PATH}" ")sql\";\n")